{% set name = "langchain-classic" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-','_') }}-{{ version }}.tar.gz
  sha256: 40a499684df36b005a1213735dc7f8dca8f5eb67978d6ec763e7a49780864fdc
  patches:
    - fix_tests.patch

build:
  number: 0
  skip: true # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - langchain-core >=1.2.5,<2.0.0
    - langchain-text-splitters >=1.1.0,<2.0.0
    - langsmith >=0.1.17,<1.0.0
    - pydantic >=2.7.4,<3.0.0
    - sqlalchemy >=1.4.0,<3.0.0
    - requests >=2.0.0,<3.0.0
    - pyyaml >=5.3.0,<7.0.0
    - async-timeout >=4.0.0,<5.0.0 # [py<311]

# ModuleNotFoundError: No module named 'syrupy'
# ModuleNotFoundError: No module named 'lark'
{% set ignored_tests = [
  "--ignore=tests/unit_tests/runnables/test_openai_functions.py",
  "--ignore=tests/unit_tests/load/test_dump.py",
  "--ignore=tests/unit_tests/test_imports.py",
  "--ignore=tests/unit_tests/test_pytest_config.py",
  "--ignore=tests/unit_tests/chains/query_constructor/test_parser.py",
  "--ignore=tests/unit_tests/retrievers/self_query/test_base.py"
]%}

{% set deselected_tests_win = [
  "--deselect=tests/unit_tests/storage/test_filesystem.py::test_mset_chmod[700-600]",
  "--deselect=tests/unit_tests/storage/test_filesystem.py::test_mset_chmod[770-660]"
]%}

test:
  source_files:
    - tests
    - pyproject.toml
  imports:
    - langchain_classic
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest tests/unit_tests -vv {{ ignored_tests | join(" ") }} # [unix]
    - pytest tests/unit_tests -vv {{ ignored_tests | join(" ") }} {{ deselected_tests_win | join(" ") }} # [win]
  requires:
    - pip
    - python
    - toml
    - numpy
    - pandas
    - pytest-socket
    - pytest-asyncio
    - pytest-mock
    - freezegun
    - pytest >=8.0.0,<9.0.0
    - langchain-openai

about:
  home: https://github.com/langchain-ai/langchain
  doc_url: https://reference.langchain.com/python/langchain_classic
  summary: Building applications with LLMs through composability
  description: |
    LangChain Classic is a framework for developing applications powered by language models.
  dev_url: https://github.com/langchain-ai/langchain/tree/master/libs/langchain
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ccurme
    - mdrxy
